DROP TABLE IF EXISTS TECH_DETAILS_TB;
 
CREATE TABLE TECH_DETAILS_TB (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  framework VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);